
domain: mgmt.bahsoftwarefactory.com
istio:
  enabled: true
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"
      kubernetesResourceSpec:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "kubernetes.io/cluster/rke2=owned,env=managment,ingress-type=public"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          kubernetes.io/tls-acme: "true"
          cert-manager.io/common-name: "*.mgmt.bahsoftwarefactory.com"
          external-dns.alpha.kubernetes.io/hostname: "*.mgmt.bahsoftwarefactory.com"
          service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
  gateways:
    public:
      hosts:
        - "*.{{ .Values.domain }}"
      tls:
        credentialName: wildcard-mgmt.bahsoftwarefactory.com

istiooperator:
  enabled: true
kiali:
  enabled: true
jaeger:
  enabled: false
eckoperator:
  enabled: false
flux:
  interval: 1m
  rollback:
    cleanupOnFail: false
logging:
  enabled: false
monitoring:
  enabled: true
  sso:
    enabled: true
    prometheus:
      client_id: "prometheus"
    alertmanager: 
      client_id: "alertmanager"
    grafana:  
      client_id: "grafana"
      tls_skip_verify_insecure: true
      scopes: "Grafana"
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
fluentbit:
  enabled: false
clusterAuditor:
  enabled: false
gatekeeper:
  enabled: false
kyverno:
  enabled: false
twistlock:
  enabled: false
addons:
  keycloak:
    enabled: false
  gitlabRunner:
    enabled: false
  gitlab:
    enabled: false
  vault:
    enabled: false
