apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:Osdxh/78wqMqj9NyCke++z2MNN6ytjGpbzN1gkYNIyDbNR7VCIilUK4YstzBqb3R9a0GkJPuwDzqpikUe/VxidAd4C0Y7kF1xgWytf+Ga02unhssILNxqx3BhEJ8jjN2RtJFRij3CnYDnZ0vibpUrbQWDBQtxOgJhrve/eFcsoO7T50ZjLNxS/tEizdVERlMO6rrLFpkNpDmgN6I85NnUMo2MazBB5yyCQAjUaiGmpIADnN3kHfXZzCxYZVxOkcJX7+NFxdl5OOR/XKIKXzARfljLRifSNlGhlfdST5nSd3K6arcs42OAXjnhw/NwSQ1bc4WQRnv+9G3qSn81Pn86E9/9kPucIO4r7hGLluYtTJ0dbfvOBLWBlig1PgVPCdJBefCyO+d9OuOfpXCNDszBg/4qIL60skpOvoGuxGUX2weq+BpV7RURW8u,iv:dnBGOKjfmpZuWOv7O+3OVMjGZTAj+mCoSLZRPnbMgEI=,tag:3gdcB/Ya5Zt1oJI5/l77JA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:729651203190:key/48cbff42-3fbc-4f93-84fc-2cde7af46a3a
          created_at: "2022-08-02T21:57:51Z"
          enc: AQICAHjAEcEpirymm+7zSBo4oNgHNAnQub+yTd5wjbIGgNxpDgGg0/y/uEWRxjS0ubPxEP6yAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNTjN7LOmOu6Ix1POAgEQgDumzxBv4E5pZ2PP6ZZ2n/LNBpGW/7qzu+Q9W1DvGtGcgr6Vzwzhezisvzxp2IUD7owz8fuEBCIQ9fN/Fw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-10T18:55:31Z"
    mac: ENC[AES256_GCM,data:68rx4aXfoYvT//iFfSi94BsYT4XC68qMqYzz7ZXOACfdN5sVuadu/YvNdac/2KPUsrpgBP/eHssyiT67vATy31lmMYSAbSe0v2KgUXhrWvEPwOeKsYJmV7zSVSCQAsZkN3jMHpzH1sOzvh92laai1xV4L/lZBB2a4cEbxbK7SmY=,iv:QvDeBziQN14Ok4tW/T/ziJ6Q9aXIMhWpJQlOAuT+ovw=,tag:AQH2eL1LLx/hPOH0DbQ21Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets.yml)$
    version: 3.7.3
