bases:
- ../base
configMapGenerator:
  - name: environment
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
## Enable the line below if a secrets.enc.yaml is created in this directory
- secrets.enc.yaml
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta2
  kind: GitRepository
  metadata:
    name: bigbang
  spec:
    interval: 1m
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: bigbang
  spec:
    interval: 1m

