
domain: "ssc.bahsoftwarefactory.com"

istio:
  enabled: true
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"
      kubernetesResourceSpec:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "kubernetes.io/cluster/ssc=owned,ingress-type=public"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          external-dns.alpha.kubernetes.io/hostname: "*.ssc.bahsoftwarefactory.com"
          service.beta.kubernetes.io/load-balancer-source-ranges: "156.80.4.2/32, 10.40.7.0/24, 10.40.8.0/24, 10.40.9.0/24"
          service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-04987f9522e27a836, subnet-069fd7685cca4018a, subnet-08942469f925d9b66"
  gateways:
    public:
      hosts:
        - "*.{{ .Values.domain }}"
      tls:
        credentialName: "public-cert"

istiooperator:
  enabled: true

kiali:
  enabled: false
jaeger:
  enabled: false
eckoperator:
  enabled: false
flux:
  interval: 1m
  rollback:
    cleanupOnFail: false
logging:
  enabled: false
monitoring:
  enabled: true
  sso:
    enabled: false
    prometheus:
      client_id: "prometheus"
    alertmanager: 
      client_id: "alertmanager"
    grafana:  
      client_id: "grafana"
      tls_skip_verify_insecure: true
      scopes: "Grafana"
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
loki:
  enabled: true
promtail: 
  enabled: true
  values:
    config:
      snippets:
        extraScrapeConfigs: |
          - job_name: journal
            journal:
              path: /var/log/journal
              max_age: 12h
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels:
                  - __journal__hostname
                target_label: hostname
              - source_labels:
                  - __journal__systemd_unit
                target_label: unit
              - source_labels:
                  - __journal_priority_keyword
                target_label: level

          - job_name: audit
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: audit
                  __path__: /var/lib/rancher/rke2/server/logs/audit.log
                  hostname: ${HOSTNAME}
    extraVolumes:
      - name: journal
        hostPath:
          path: /var/log/journal
      - name: machine-id
        hostPath:
          path: /etc/machine-id
      - name: audit
        hostPath:
          path: /var/lib/rancher/rke2/server/logs/audit.log
    extraVolumeMounts:
      - name: journal
        mountPath: /var/log/journal
        readOnly: true
      - name: machine-id
        mountPath: /etc/machine-id
        readOnly: true
      - name: audit
        mountPath: /var/lib/rancher/rke2/server/logs/audit.log
        readOnly: true
    extraArgs:
      - '-config.expand-env'
fluentbit:
  enabled: false
clusterAuditor:
  enabled: false
gatekeeper:
  enabled: false
kyverno:
  enabled: false
twistlock:
  enabled: false
addons:
  keycloak:
    enabled: false
  gitlabRunner:
    enabled: false
  gitlab:
    enabled: false
  vault:
    enabled: false
