kubectl get mutatingwebhookconfigurations,validatingwebhookconfigurations,wasmplugins,istiooperators,destinationrules,envoyfilters -A
kubectl get gateways,proxyconfigs,serviceentries,sidecars,virtualservices,workloadentries,workloadgroups,authorizationpolicies -A
kubectl get peerauthentications,requestauthentications,telemetries -A
