domain: dev.bahsoftwarefactory.com

istio:
  enabled: true
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"
      kubernetesResourceSpec:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "false"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-name: "development-istio-ingress"
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "kubernetes.io/cluster/c-m-xgd7cmkn=owned"
          service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=false,deletion_protection.enabled=false"
          service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0604239537880429e,subnet-097be7160f7469241,subnet-0ae69f6e25ba9ba92"
