apiVersion: v1
kind: Namespace
metadata:
  name: bigbang
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: environment-repo
  namespace: bigbang
spec:
  interval: 1m
  url: https://github.com/bah-kvn/bigbang.git
  ref:
    branch: main
  secretRef:
    name: private-git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./rmc
  prune: true
  decryption:
    provider: sops



