
domain: "rmc.bahsoftwarefactory.com"

istio:
  enabled: true
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"
      kubernetesResourceSpec:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "kubernetes.io/cluster/rmc=owned,ingress-type=public"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          external-dns.alpha.kubernetes.io/hostname: "*.rmc.bahsoftwarefactory.com"
          service.beta.kubernetes.io/load-balancer-source-ranges: "156.80.4.2/32, 10.40.7.0/24, 10.40.8.0/24, 10.40.9.0/24"
          service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-04987f9522e27a836, subnet-069fd7685cca4018a, subnet-08942469f925d9b66"
  gateways:
    public:
      hosts:
        - "*.{{ .Values.domain }}"
      tls:
        credentialName: "public-cert"

istiooperator:
  enabled: true

kiali:
  enabled: false
jaeger:
  enabled: false
eckoperator:
  enabled: false
flux:
  interval: 1m
  rollback:
    cleanupOnFail: false
logging:
  enabled: false
monitoring:
  enabled: false
  sso:
    enabled: true
    prometheus:
      client_id: "prometheus"
    alertmanager: 
      client_id: "alertmanager"
    grafana:  
      client_id: "grafana"
      tls_skip_verify_insecure: true
      scopes: "Grafana"
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
fluentbit:
  enabled: false
clusterAuditor:
  enabled: false
gatekeeper:
  enabled: false
kyverno:
  enabled: false
twistlock:
  enabled: false
addons:
  keycloak:
    enabled: false
  gitlabRunner:
    enabled: false
  gitlab:
    enabled: false
  vault:
    enabled: false
