# yamllint disable rule:truthy
---
name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install shellcheck
      - run: |
          echo github.ref is: ${{ github.ref }}
          echo github.event_name is: ${{ github.event_name }}
      - run: head -25 ./scripts/01-script.sh
      - name: Run shell linting
        run: shellcheck --format=gcc **/*.sh
